In [ ]:
# LSTM for sequence modeling
# /Users/akuppam/Documents/Pythprog/deep_learning_bundle/.....
# .....long_short_term_memory_networks_with_python/code/lesson_06

In [4]:
from random import randint
from numpy import array
from numpy import argmax
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

# generate a sequence of random numbers in [0, n_features)
def generate_sequence(length, n_features):
	return [randint(0, n_features-1) for _ in range(length)]

# one hot encode sequence
def one_hot_encode(sequence, n_features):
	encoding = list()
	for value in sequence:
		vector = [0 for _ in range(n_features)]
		vector[value] = 1
		encoding.append(vector)
	return array(encoding)

# decode a one hot encoded string
def one_hot_decode(encoded_seq):
	return [argmax(vector) for vector in encoded_seq]

# generate one example for an lstm
def generate_example(length, n_features, out_index):
	# generate sequence
	sequence = generate_sequence(length, n_features)
	# one hot encode
	encoded = one_hot_encode(sequence, n_features)
	# reshape sequence to be 3D
	X = encoded.reshape((1, length, n_features))
	# select output
	y = encoded[out_index].reshape(1, n_features)
	return X, y

# define model
length = 5
n_features = 10
out_index = 2
model = Sequential()
model.add(LSTM(25, input_shape=(length, n_features)))
model.add(Dense(n_features, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
print(model.summary())

# fit model
for i in range(10):
	X, y = generate_example(length, n_features, out_index)
	model.fit(X, y, epochs=1, verbose=2)

# evaluate model
correct = 0
for i in range(100):
	X, y = generate_example(length, n_features, out_index)
	yhat = model.predict(X)
	if one_hot_decode(yhat) == one_hot_decode(y):
		correct += 1
print('Accuracy: %f' % ((correct/100)*100.0))

# prediction on new data
X, y = generate_example(length, n_features, out_index)
yhat = model.predict(X)
print('Sequence:  %s' % [one_hot_decode(x) for x in X])
print('Expected:  %s' % one_hot_decode(y))
print('Predicted: %s' % one_hot_decode(yhat))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 25)                3600      
_________________________________________________________________
dense_4 (Dense)              (None, 10)                260       
Total params: 3,860
Trainable params: 3,860
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/1
 - 1s - loss: 2.2279 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2502 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2430 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3172 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2858 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2978 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3391 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2090 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2762 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2533 - acc: 0.0000e+00
Accuracy: 18.000000
Sequence:  [[6, 6, 3, 8, 4]]


In [5]:
X

array([[[0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]]])

In [6]:
y

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]])

In [ ]:
Accuracy: 7.000000
Sequence:  [[6, 9, 5, 4, 2]]
Expected:  [5]
Predicted: [3]

In [ ]:
Accuracy: 18.000000
Sequence:  [[2, 0, 8, 5, 9]]
Expected:  [8]
Predicted: [7]

In [ ]:
Accuracy: 9.000000
Sequence:  [[1, 4, 9, 3, 8]]
Expected:  [9]
Predicted: [6]

In [ ]:
# generate one example for an lstm
def generate_example(length, n_features, out_index):
  # generate sequence
  sequence = generate_sequence(length, n_features)
  # one hot encode
  encoded = one_hot_encode(sequence, n_features)
  # reshape sequence to be 3D
  X = encoded.reshape((1, length, n_features))
  # select output
  y = encoded[out_index].reshape(1, n_features)
return X, y

In [57]:
length = 5
n_features = 10
out_index = 2
sequence = generate_sequence(length, n_features)
encoded = one_hot_encode(sequence, n_features)
X = encoded.reshape((1, length, n_features))
y = encoded[out_index].reshape(1, n_features)

In [58]:
sequence

[7, 3, 2, 6, 8]

In [59]:
encoded

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [60]:
X

array([[[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]]])

In [61]:
y

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [43]:
y = encoded[4]
y

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [49]:
X = encoded.reshape(1, 5, 10)
X

array([[[0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]]])

In [55]:
y = encoded[1, :]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [62]:
yhat - model.predict(X)
yhat

array([[0.1050853 , 0.10310294, 0.09943166, 0.08954316, 0.10288467,
        0.09983714, 0.10728016, 0.10032192, 0.09465036, 0.09786275]],
      dtype=float32)